"""
Simple GAN‑based synthetic face generator used to illustrate a GAN‑driven threat
scenario. The generator is deliberately lightweight (DCGAN‑style) so it can run
on CPU without heavy dependencies. Generated images are fed through the same
BlazeFace pipeline, allowing us to measure detection latency on on‑the‑fly
deepfakes.
"""

import torch
import torch.nn as nn
import numpy as np

class SimpleGenerator(nn.Module):
    """A minimal DCGAN generator mapping a 100‑dim noise vector to a 64×64 RGB image.
    The network is intentionally shallow – suitable for a quick demo without
    GPU requirements. If CUDA is available it will be used automatically.
    """
    def __init__(self, nz: int = 100, ngf: int = 64, nc: int = 3):
        super().__init__()
        self.nz = nz
        self.main = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh()  # output in [-1, 1]
        )
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.to(self.device)
        self.eval()

    def forward(self, noise: torch.Tensor):
        return self.main(noise)

def generate_synthetic_face(seed: int | None = None) -> np.ndarray:
    """Return a 64×64 uint8 RGB image generated by the tiny DCGAN.
    The generator is instantiated on each call (lightweight) and uses random
    weights – the goal is to produce *some* facial‑like pattern to illustrate a
    GAN‑driven deepfake threat, not a high‑fidelity synthetic image.
    """
    if seed is not None:
        torch.manual_seed(seed)
        np.random.seed(seed)
    gen = SimpleGenerator()
    noise = torch.randn(1, gen.nz, 1, 1, device=gen.device)
    with torch.no_grad():
        img_tensor = gen(noise).cpu()
    # Convert from [-1, 1] to [0, 255]
    img_np = ((img_tensor.squeeze(0).permute(1, 2, 0).numpy() + 1) * 127.5).astype(np.uint8)
    return img_np
